POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2N2YzMTgyLTU4OGEtNDBhMy04NzQ5LTJmYTcyYzMwYzQ3ZCIsImlhdCI6MTczODg1OTY0NywiZXhwIjoxNzM4ODYzMjQ3fQ.ldadLWuUE5vjK45LbJ-_dC5XBRjsTEa00HOWIKNYA84

{
    "title": "Task 1",
    "description": "Description 1"
}